version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: "Setup custom ENV variables"
                command: echo "export SERVICE_ACCOUNT_PRIVATE_KEY=$(echo $SERVICE_ACCOUNT_PRIVATE_KEY_BASE64 | base64 -d)" >> $BASH_ENV
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
